name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          # copy src to docker container XD (temp)
          script: |
            echo $(date) >> transafe-latest-update.txt
            cd ~/transafe && git pull origin main
            docker cp app/src dffd2b2da083:/usr/src/app/  